// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	Verified  pgtype.Bool
	CreatedAt pgtype.Timestamp
}
