// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    last_name,
    username,
    password,
    email
)
VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, last_name, username,email,verified
`

type CreateUserParams struct {
	Name     string
	LastName string
	Username string
	Password string
	Email    string
}

type CreateUserRow struct {
	ID       int32
	Name     string
	LastName string
	Username string
	Email    string
	Verified pgtype.Bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.LastName,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Username,
		&i.Email,
		&i.Verified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, last_name, username, password, email, verified, created_at, last_updated, plan_id FROM users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
		&i.LastUpdated,
		&i.PlanID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, last_name, username, password, email, verified, created_at, last_updated, plan_id FROM users
where id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Verified,
		&i.CreatedAt,
		&i.LastUpdated,
		&i.PlanID,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $1,
    last_name = $2, 
    username = $3,
    password =$4,
    email = $5,
    plan_id = $6,
    last_updated = now()
WHERE id = $7
`

type UpdateUserParams struct {
	Name     string
	LastName string
	Username string
	Password string
	Email    string
	PlanID   pgtype.Int4
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.LastName,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.PlanID,
		arg.ID,
	)
	return err
}

const verifyUser = `-- name: VerifyUser :execrows
UPDATE users
SET verified = true
WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, verifyUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
