// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc_code

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int32
	Balance   pgtype.Float8
	Currency  string
	CreatedAt pgtype.Timestamp
	UserID    pgtype.Int4
}

type Transfer struct {
	ID        int32
	Amount    float64
	Reason    pgtype.Text
	AccountID pgtype.Int4
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamp
	Verified  pgtype.Bool
}
